[build]
    base = ""
    build = "build"
    command = "npm run build"
    
[build.environment]	
    NODE_ENV = "development"	

[context.production.environment]	
    NODE_ENV = "production"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200